#!/bin/bash

# Check if a custom directory is provided
if [ -z "$1" ]; then
    echo "Move grid parameters to ./chkpt_state/"
    dirname="chkpt_state"
else
    echo "Move grid parameters to user's directory: $1"
    dirname=$1
fi

# Make grid directory
mkdir -p "$dirname"

# Move grid parameters
mv -v Eta.*.[dm][ae]ta \
PH.*.[dm][ae]ta \
PHL.*.[dm][ae]ta \
[STUVW].*.[dm][ae]ta \
"$dirname"
